### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by lubrand** [hedra-editora/platao_fedro#2]
### Capa

* [ ] Recalcular Lombada
* [x] Conferir Formato (altura, largura e tamanho da orelha)
* [x] Conferir Coleção
* [x] Título: ler pausadamente título da capa e do miolo
* [x] Autor: item
* [x] Trecho de capa: conferir com Miolo
* [x] Texto de orelha: leitura de duas pessoas
* [x] Imagem de capa (não esquecer de colocar crédito de imaem depois dentro do livro)
* [x] Nome do capista nos créditos
* [x] Isbn (Mandar imagem EPS): conferir com planilha no google drive em goo.gl/QYVTex
Se for bolso:
* [x] Rubricas de capa devem ter gênero: "Autor" "Autora"
* [x] Seguir modelo _Organização e tradução do grego_
* [x] Verificar se obra não faz parte de subcoleção
* [x] Verifcar no miolo se constam resumos do autor, da obra e das pessoas envolvidas. Se houver subcoleção, verificar se existe também texto sobre.

### Página de crédito (fichatecnica.sty)

Ex: \newcommand{\<COMANDO>}{<CONTEÚDO>} em fichatecnica.sty (na pasta do livros)

Lista de comandos:
* [x] \titulo  				
* [x] \subtit  				
* [x] \autor  				
* [x] \ISBN
* [ ] \eISBN
* [x] \ano
* [x] \organizador  				
* [x] \introdutor			
* [x] \tradutor  				
* [x] \prefacio  				
* [x] \apresentador  				
* [x] \edicao{Jorge Sallum}
* [x] \coedicao
* [x] \assistencia
* [x] \revisao
* [x] \preparacao
* [x] \capa
* [x] \imagemcapa  				
* [x] \agradecimentos
* [x] \indicacao
* [x] \copyrightlivro
* [x] \copyrighttraducao
* [x] \copyrightorganizacao
* [x] \copyrightilustracao
* [x] \copyrightintroducao
* [x] \titulooriginal
* [x] \edicaoconsultada
* [x] \primeiraedicao
* [x] \grafica  				
* [x] \papelmiolo  				
* [x] \gramaturamiolo  				

### Fechamento

* [ ] arquivo de EPUB em \ARQUIVOSGERAIS\EPUB
* [x] verificar se código ID no final do livro bate com a versão do github
* [x] arquivo de miolo está em \ARQUIVOSGERAIS?
* [x] arquivo de capa está em \ARQUIVOSGERAIS?
* [x] arquivos estão em github?
* [x] checklist de página de crédito
* [ ] Criar MO de lançamento 

### Cadastros

 * Internos
	* Odoo (@jorgesallum)
	* Site (@anaclara)
 * Indexadores (metadados)
	* Mercado editorial (@anaclara)
	* Metabooks @(jorgesallum)
 * Integradores (distribuição, PoD, logística, pagamentos)
	* Meta (@jorgesallum)
	* Bookwire (@rodney)
 * Repositórios ("netflix")
	* Nuvem de livros (@jorgesallum)
	* Árvore de livros (@luiza)

=========================================
Pré-venda (dia 3) DROPBOX/PRODUCAO/PREVENDA

* [ ] Com o autor: Lançamentos marcado?
* [ ] Com o autor: Lista vip do autor
* [ ] Com o autor: Lista de jornalista
* [x] Booklet (x30)
* [x] Release
* [x] Cadastro da Bookwire (como pré-venda)
* [ ] Imagem de capa em alta

Conteúdo

* [x] Texto para blog
* [ ] _Newsletter_ para clientes
* [ ] Texto para Facebook
* [ ] Texto para Instagram
* [ ] Tuites

Extra-editorial

* [ ] parceiros de divulgacao (blogueiros)
* [ ] kit para imprensa (envio)

=========================================
Comercial (editorial acompanha)

* [ ] Apresentação para compradores (@ricardo)
* [ ] Tiragem mínima para impressão
* [ ] Cadastros

=========================================
Fechamento (dia 10)

* [ ] Arquivos OK
* [ ] Repositórios
* [ ] Exemplares para autor (10-20 exemplos)
* [ ] Lançamento (chegada do livro)

**Comment by lubrand** [comment]
Capa já está fechada?
